# Generated by Django 3.2.23 on 2024-01-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
